### ISSUE TITLE
JdbcRepositories.initRepositoryJSON  逆向生成json文件跟工程里面带的repository.json格式不一致的问题

### ISSUE THREAD

**Issue by songjindian** [b3log/latke#101]
用JdbcRepositories.initRepositoryJSON 可以根据数据库的表来生成repository.json 中的json内容，但是目前根据生成的情况来说有点问题：

1. 生成的json对象的属性跟repository.json不一致，比如缺少表的描述信息，"description": "浏览表"
2. 生成的表名问题，repository.json中的表名不带前缀，例如visit，对应的数据库表名带前缀的symphony_visit。

Set<String> tableNames = new TreeSet<String>();
		tableNames.add("symphony_user_info");
		JdbcRepositories.initRepositoryJSON(tableNames, "E:\\resources\\repository_ext.json");

这样能生成symphony_user_info的json信息，在json文件中表名为symphony_user_info，但是如果我再代码中这么写tableNames.add("user_info");也就是去掉前缀，那么就不会生成json内容。

**Comment by 88250** [comment]
示例参考 https://github.com/b3log/symphony/blob/master/src/test/java/org/b3log/symphony/RepositoryJSONGen.java
