### ISSUE TITLE
支持按环境进行配置切换

### ISSUE THREAD

**Issue by westinyang** [b3log/latke#104]
类似 springboot application.properties 中配置的激活哪个配置文件。
这样可以保留两份配置文件快速切换，一个symphony-dev.properties，一个symphony-prod.properties

**Comment by 88250** [comment]
通过环境变量支持配置切换，这样对运维更简单一些： https://github.com/b3log/symphony/issues/695
对于 Sym 这个项目，你可以通过改造 symphonys 工具类来达到这个目的。
