### ISSUE TITLE
latke框架的json对象和表结构之间的映射规则是什么？

### ISSUE THREAD

**Issue by wang18140673019** [b3log/latke#115]
在接触solo和latke之前，我一直是用`通用mapper`(一个mybatis插件)，根据实体类自动生成单表单表的增删改查，现在遇到了一个问题，我无法写出sql语句，原因是无法确定json对象和表结构之间的映射规则

**Comment by 88250** [comment]
* JSON key-value 对应表的列-值
* Repository 对应表
