### ISSUE TITLE
是否有必要脱离 Servlet 容器

### ISSUE THREAD

**Issue by 88250** [b3log/latke#139]
1. Servlet 容器比较重，并且很多特性没有使用必要
2. 基于 HTTP 网络库已经可以满足使用需求
    * Netty
    * https://github.com/NanoHttpd/nanohttpd
    * JDK >= 11 java.net.HTTP.*

大重旧慢 -> 小轻新快？

**Comment by nuaacyy** [comment]
D大 关于latke 接下来有没有什么发展路线图？接下来会添加哪些新特性？

**Comment by 88250** [comment]
> D大 关于latke 接下来有没有什么发展路线图？接下来会添加哪些新特性？

暂时不会添加大的特性了，保持小巧轻量。考虑到 Solo 还有一些用户是部署在 Servlet 容器中，所以脱离 Servlet 容器的重构计划也暂时搁置。总的来说就是暂时保持现状，等 Solo、Sym 等应用或者其他有人有需求再继续考虑发展路线。

**Comment by 88250** [comment]
还差文件上传处理没做，其他基本已经 OK，发布 v3.0.0。
