### ISSUE TITLE
JDK11 插件加载问题

### ISSUE THREAD

**Issue by 88250** [b3log/latke#154]
https://github.com/b3log/solo/issues/12672

**Comment by 88250** [comment]
诊断跟进 https://hacpai.com/article/1561591793635/comment/1561651273006

感谢 @yanxingangsun :heart:

**Comment by yanxingangsun** [comment]
JDK11 以上插件加载会报错。问题不是出在 solo 上，而是出在 latke-core 的 `org.b3log.latke.plugin.PluginManager` 的代码上，问题代码如下：
```
final URLClassLoader classLoader = new URLClassLoader(new URL[]{
                defaultClassesFileDirURL, classesFileDirURL}, PluginManager.class.getClassLoader());	
```
首先defaultClassesFileDirURL这个变量一般情况下值为null, 在defaultClassesFileDirURL==null的情况下，
- 在 java1.8 版本情况下运行不会抛出异常；
- 在 java11 以后版本情况下运行会抛出异常；
在抛出异常后插件加载失败。把上面代码改成如下形式，问题即可解决：
```
	URLClassLoader classLoader=null;

        if(defaultClassesFileDirURL==null){
            classLoader = new URLClassLoader(new URL[]{
                classesFileDirURL}, PluginManager.class.getClassLoader());
        }
        else{
            classLoader = new URLClassLoader(new URL[]{
                defaultClassesFileDirURL, classesFileDirURL}, PluginManager.class.getClassLoader());
        }
```
