### ISSUE TITLE
Redis 存储支持

### ISSUE THREAD

**Issue by 88250** [b3log/latke#59]
目前支持 3 种数据库产品：
- H2
- MySQL
- SQLServer

将会再新增支持一种数据存储产品： Redis ，多条件查询可能实现不了，需要再看下。

**Comment by linkerlin** [comment]
如果能支持Neo4J就更加牛了！

**Comment by 88250** [comment]
@linkerlin 理论上可以支持的，欢迎 PR 贡献。

**Comment by 88250** [comment]
改成缓存实现算了  https://github.com/b3log/latke/issues/68
