### ISSUE TITLE
latke 中关于数据查询的实现与缓存

### ISSUE THREAD

**Issue by TiSongWen** [b3log/latke#63]
latke 中关于数据查询的实现（即替代ORM功能），对查询出来的对象是否会进行缓存呢？ 如果有，那么是否要考虑对象缓存生命周期的管理呢？ 

所以想请教下造轮子的您。^ ^ 感谢您即将的回答。

**Comment by 88250** [comment]
repository 以前做过缓存，后来移除了，缓存最好还是在应用中自己做。

#39 
#40

**Comment by TiSongWen** [comment]
比如 hibernate 一共有两级缓存，是说这个缓存在应用中自己做吗？
为什么 在分布式环境中，节点的数据缓存是个错误的设计呢？

**Comment by 88250** [comment]
分布式环境中要用分布式缓存，节点内部的内存缓存会带来一致性问题。

**Comment by TiSongWen** [comment]
嗯呢。十分感谢D的解答。 ^ ^

**Comment by 88250** [comment]
装完 B 我要跑了。
