### ISSUE TITLE
更安全地保存 Cookie 

### ISSUE THREAD

**Issue by 88250** [b3log/latke#70]
目前 cookie 是直接以 JSON 字符串格式写入浏览器的，存在两个问题：

1. 不安全，暴露了用户邮箱和密码
2. Tomcat 某些版本对 cookie 值有校验，[现象参考](https://hacpai.com/article/1502285822296)

改造方案：

1. latke.props 中加入 `cookieSecret`，作为 cookie 值加/解密的密钥生成 key
2. 使用 AES 算法对 JSON 字符串进行加密后写入 cookie

**Comment by nanolikeyou** [comment]
另外建议setcookie时设置httponly属性

**Comment by 88250** [comment]
@nanolikeyou 加了个 `cookieHttpOnly` 的配置，默认是 `false`。Solo 里面暂时也不开启，因为用了 JS 取 cookie。

**Comment by wizardforcel** [comment]
跟 Discuz 的方案差不多。除了算法不一样之外。
