### ISSUE TITLE
关于访客IP的真实性问题

### ISSUE THREAD

**Issue by nanolikeyou** [b3log/latke#75]
String ret = request.getHeader("X-forwarded-for");

        if (Strings.isEmptyOrNull(ret)) {
            ret = request.getHeader("X-Real-IP");
        }

        if (Strings.isEmptyOrNull(ret)) {
            return request.getRemoteAddr();
        }

        return ret.split(",")[0];
在utils下的Request类getRemoteAddr方法中，存在通过修改header字段X-forwarded-for或X-Real-IP伪造访客ip的情况。直接使用request.getRemoteAddr();即可。

**Comment by 88250** [comment]
这些头主要是在反向代理服务器上面设置的。
