### ISSUE TITLE
汉字url访问静态资源失效

### ISSUE THREAD

**Issue by ACEsLegendary** [b3log/latke#78]
RT。为了关联本地的一些静态资源，主要是一些doc文档，在static-resources.xml中配置了自己的静态资源匹配模式之后，资源url中不包含中文的时候，可以正常处理，但是如果资源url中包含中文的时候,latke似乎无法识别urlencoded过后的url。

**Comment by 88250** [comment]
master 上已经修复，可以自己编译或者等过几天发布 v2.3.20 到中央库。
