### ISSUE TITLE
防止文件夹内容误伤的修改

### ISSUE THREAD

**Issue by JYSimonGit** [b3log/latke#85]
建议将JdbcRepositories#initRepositoryJSON 方法中FileUtils.deleteQuietly(file);代码增加目录判断，如果是目录建议返回报错信息，而不是直接删除。  initRepositoryJSON方法参数为destPath，也容易让人以为是文件夹路径而非文件 file。

**Comment by 88250** [comment]
已经提交修改，请参考最新代码。
