### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by 88250** [b3log/latke#95]
是时候画个 logo 了。

**Comment by richardbmx** [comment]
@88250 Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by richardbmx** [comment]
Perfect can you tell me what the project is about and the main function in order to make a logo that expresses well the functions of your project

**Comment by 88250** [comment]
@richardbmx You could find it in README.

**Comment by richardbmx** [comment]
@88250  I present my proposal, the design is based on giving a unique and minimalist style to the letter L (initial name of your project) to give your own unique personality to your project.

If you want something to change or have an idea in mind do not hesitate to say it to make it

![logo98](https://user-images.githubusercontent.com/35604837/44303259-faa5c080-a309-11e8-97de-0c2da2025c44.png)

**Comment by richardbmx** [comment]
Perfect that you want to add?

I look for the definition of Latke but I do not know if you want to express the pancake in the design :-)

**Comment by 88250** [comment]
So this may be the difficulty of this design.

**Comment by richardbmx** [comment]
@88250  I'm working in it
;-)

**Comment by 88250** [comment]
已经由黑客派社区的 windsays 帮忙设计完成： https://hacpai.com/article/1542962638657

![latke](https://user-images.githubusercontent.com/873584/52535068-de4c8300-2d84-11e9-92f6-afe60feb523e.png)
